import pandas as pd
import glob
import os

'''
merge all the csvs within one directory into one massive csv
(generated by Gemini)
'''
def merge_csv_files(input_folder, output_filename):
    # Search for all csv files in the specified folder
    path = os.path.join(input_folder, "*.csv")
    all_files = glob.glob(path)

    if not all_files:
        print("No CSV files found in the directory.")
        return

    print(f"Found {len(all_files)} files. Starting merge...")

    # Create a list of dataframes
    # We use a list comprehension for better performance
    df_list = [pd.read_csv(filename) for filename in all_files]

    # Concatenate all dataframes in the list into one
    combined_df = pd.concat(df_list, axis=0, ignore_index=True)

    # Save to a new CSV
    combined_df.to_csv(output_filename, index=False)
    print(f"Success! Merged file saved as: {output_filename}")

# --- Configuration ---
folder_path = './wall_test_0'  # Change this to your folder path
output_file = 'ALL_wall_test_0.csv'   # The name of your new big file

merge_csv_files(folder_path, output_file)